import BreadCrumb from '@/components/common/BreadCrumb'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <>
      {/* <BreadCrumb /> */}
      {children}
    </>
  )
}
